import alfy from 'alfy';

var obj = []
obj.push({
    title: "10秒後",
    subtitle: 10,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"10"
});
obj.push({
    title: "30秒後",
    subtitle: 30,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"30"
});
obj.push({
    title: "1分後",
    subtitle: 60,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"60"
});
obj.push({
    title: "3分後",
    subtitle: 180,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"180"
});
obj.push({
    title: "5分後",
    subtitle: 300,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"300"
});
obj.push({
    title: "10分後",
    subtitle: 600,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"600"
});
obj.push({
    title: "30分後",
    subtitle: 1800,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"1800"
});
obj.push({
    title: "60分後",
    subtitle: 3600,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"3600"
});
obj.push({
    title: "3時間後",
    subtitle: 10800,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"10800"
});
obj.push({
    title: "5時間後",
    subtitle: 3600*5,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"18000"
});
obj.push({
    title: "24時間後",
    subtitle: 3600*24,
    icon: {path: './img/main03.jpg'},
    arg: alfy.input+"&"+"86400"
});


alfy.output(obj);

//2022-05-15 01:47:45 は、Unixtimeの 1652546865です
//2022-05-15 01:48:45 は、Unixtimeの 1652546925です
//2022-05-15 01:58:45 は、Unixtimeの 1652547525です
//2022-05-15 02:58:45 は、Unixtimeの 1652551125です
//2022-05-16 01:58:45 は、Unixtimeの 1652633925です


//responsは以下

// {
//     ok: true,
//     channels: [
//       {
//         id: 'CQ7CFSU5N',
//         name: 'general',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1573030256,
//         is_archived: false,
//         is_general: true,
//         unlinked: 0,
//         name_normalized: 'general',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'CQ7CFSW48',
//         name: 'random',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1573030256,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'random',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'CQ7CFT32L',
//         name: 'api',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1573030257,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'api',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 7
//       },
//       {
//         id: 'C021XC2H0LD',
//         name: 'english',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1621063440,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'english',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C022GJZBYQN',
//         name: 'program_memo',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1621612211,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'program_memo',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C022HFPCYBD',
//         name: 'メモ',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1621503579,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'ﾒﾓ',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C0246RU85SR',
//         name: 'code',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1623101889,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'code',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C0250SCRWNN',
//         name: 'research',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1623708060,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'research',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C025Z9HBCFK',
//         name: 'recruit',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1624187345,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'recruit',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 3
//       },
//       {
//         id: 'C02628313RS',
//         name: 'サーバー',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1624403092,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'ｻｰﾊﾞｰ',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C028A2JDTBP',
//         name: 'youtube',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1626501605,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'youtube',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 1
//       },
//       {
//         id: 'C0392MCMU6S',
//         name: 'contents',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1648624723,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'contents',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C039MV3GVBK',
//         name: 'asana-notifications',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1648624693,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'asana-notifications',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: false,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 0
//       },
//       {
//         id: 'C039SJ3CSH4',
//         name: '田岡',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1649080585,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: '田岡',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 1
//       }
//     ],
//     response_metadata: { next_cursor: '' }
//   }
