import alfy from 'alfy';
//https://taoken.slack.com/archives/CQ7CFT32L

// 環境変数の取得
const api = "xoxb-825280440711-3327951537137-3uPxwmZKwL5VeVUutoDNKv7q"
const token = process.env.TOKEN || api
const postUrl = "https://slack.com/api/chat.postMessage";
const fetch_all_channels_url = "https://slack.com/api/conversations.list";
var obj=[];
const message = alfy.input;
//curl -H GET "https://slack.com/api/conversations.list" -H 'Content-Type:application/json;charset=utf-8' -H 'Authorization: Bearer xoxp-825280440711-825633548534-3333594547058-e6227ce6dd9860cc28a7fb5a35c42bcc' | jq .
(async() => {
    try {
        const response = await alfy.fetch(
            fetch_all_channels_url,
            {
                method: "GET",
                headers: {
                    Authorization: `Bearer ${token}`,
                },
            }
        )
        for(let i=0; i<response.channels.length; i++) {
            //console.log(response.channels[i].id)
            if (response.channels[i].is_archived || response.channels[i].num_members == 0){
                continue
            }
            obj.push({
                title: response.channels[i].name,
                subtitle: response.channels[i].id,
                icon: {path: './img/main04.jpg'},
                arg: message+"%"+response.channels[i].id+"$"+response.channels[i].name
                //arg: response.channels[i].id
            });
        }
        alfy.output(obj);
    }
    catch {
        console.log("投稿失敗しました!!!!")
    }
})();




//responsは以下

// {
//     ok: true,
//     channels: [
//       {
//         id: 'CQ7CFSU5N',
//         name: 'general',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1573030256,
//         is_archived: false,
//         is_general: true,
//         unlinked: 0,
//         name_normalized: 'general',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'CQ7CFSW48',
//         name: 'random',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1573030256,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'random',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'CQ7CFT32L',
//         name: 'api',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1573030257,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'api',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 7
//       },
//       {
//         id: 'C021XC2H0LD',
//         name: 'english',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1621063440,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'english',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C022GJZBYQN',
//         name: 'program_memo',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1621612211,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'program_memo',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C022HFPCYBD',
//         name: 'メモ',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1621503579,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'ﾒﾓ',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C0246RU85SR',
//         name: 'code',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1623101889,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'code',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C0250SCRWNN',
//         name: 'research',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1623708060,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'research',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C025Z9HBCFK',
//         name: 'recruit',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1624187345,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'recruit',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 3
//       },
//       {
//         id: 'C02628313RS',
//         name: 'サーバー',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1624403092,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'ｻｰﾊﾞｰ',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C028A2JDTBP',
//         name: 'youtube',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1626501605,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'youtube',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 1
//       },
//       {
//         id: 'C0392MCMU6S',
//         name: 'contents',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1648624723,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'contents',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 2
//       },
//       {
//         id: 'C039MV3GVBK',
//         name: 'asana-notifications',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1648624693,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: 'asana-notifications',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: false,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 0
//       },
//       {
//         id: 'C039SJ3CSH4',
//         name: '田岡',
//         is_channel: true,
//         is_group: false,
//         is_im: false,
//         is_mpim: false,
//         is_private: false,
//         created: 1649080585,
//         is_archived: false,
//         is_general: false,
//         unlinked: 0,
//         name_normalized: '田岡',
//         is_shared: false,
//         is_org_shared: false,
//         is_pending_ext_shared: false,
//         pending_shared: [],
//         parent_conversation: null,
//         creator: 'UQ9JMG4FQ',
//         is_ext_shared: false,
//         shared_team_ids: [Array],
//         pending_connected_team_ids: [],
//         is_member: true,
//         topic: [Object],
//         purpose: [Object],
//         previous_names: [],
//         num_members: 1
//       }
//     ],
//     response_metadata: { next_cursor: '' }
//   }
